name: pytorch111
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python3 == 3.8
  - pip
  - pytorch == 1.11.0
  - cudatoolkit == 11.5.1
  - yaml == 0.2.5
  - scipy == 1.8.0
  - numpy >= 1.20
  - h5py >= 3.7.0
  - tqdm == 4.63.1
  - seaborn == 0.11.2
  - matplotlib == 3.5.1
  - wandb
  - torchdiffeq
  - clean-fid
