
# model
temb_dim: 1
x_dim: 2

# SDE
beta_min: 0.1
beta_max: 20

# sample
seed: 13244
batchsize: 10000
ckpt: ddpm-final.pt
num_samples: 50000
step_size: 0.001
t_size: 65
scale: True

# log config
logname: ddpm-02
dataname: ddpm-02-train


