
# model
temb_dim: 1
x_dim: 2

# SDE
beta_min: 0.1
beta_max: 20

# sample
seed: 1500
batchsize: 5000
ckpt: score_final.pt
num_samples: 10000
step_size: 0.001
t_size: 65

# log config
logname: ddpm-01
dataname: ddpm-01


