datapath: data/25gm/25gm-train-v4-s65.pt

# model
temb_dim: 1
x_dim: 2

# SDE
beta_min: 0.1
beta_max: 20
num_scales: 1000

# training
num_epoch: 3000
batchsize: 1000
lr: 0.001
milestone: [1500]

# log config
logname: ddpm-02
save_step: 500


