# data configuration
datapath: data/25gm-train-v4.pt
# test parameter
batchsize: 500
t_dim: 50
dimension: 2
epsilon: 0.00001
ckpt: exp/gm-variance4/ckpts/solver-model_final.pt

# model
layers: [16, 16, 16, 16]
modes: [16, 16, 16]
fc_dim: 8
activation: 'gelu'


# log
logname: gm-variance4