# data configuration
datapath: data/25gm/25gm-test-v4-s65.pt
# test parameter
batchsize: 1000
t_dim: 65
t_step: 32
dimension: 2
epsilon: 0.00001
ckpt: exp/25gm-v4-FCN-300-l4-5k/ckpts/solver-model_final.pt

# model , 2, 6 - 4, 8
layers: [2, 300, 300, 300, 300, 2]
activation: 'gelu'

# log
logname: 25gm-v4-FCN-300-l4-5k