# data configuration
datapath: data/25gm/25gm-test-v4-s65.pt
# test parameter
batchsize: 1000
t_dim: 65
t_step: 16
dimension: 2
epsilon: 0.00001
ckpt: exp/25gm-v4-FCN-128/ckpts/solver-model_final.pt

# model , 2, 6 - 4, 8
layers: [2, 128, 128, 128, 128, 128, 2]
activation: 'gelu'

# log
logname: 25gm-v4-FCN