# data configuration
datapath: data/1dgm-test.pt
# training
num_epoch: 2000
batchsize: 500
t_dim: 50
dimension: 1
epsilon: 0.00001
ckpt: exp/gm-1d/ckpts/solver-model_final.pt

# model , 2, 6 - 4, 8
layers: [2, 2, 2]
modes: [4, 4]
fc_dim: 2
activation: 'gelu'


# log
logname: gm-1d
