# data configuration
datapath: data/25gm/25gm-train-v4-s65.pt
num_sample: 5000
# training
num_epoch: 4000
batchsize: 1000
lr: 0.002
t_dim: 65
t_step: 4
dimension: 2
epsilon: 0.00001
milestone: [2000]

# model , 2, 6 - 4, 8
layers: [16, 16, 16, 16]
modes: [8, 8, 8]
fc_dim: 8
activation: 'gelu'


# log
logname: 25gm-v4-s17-sample5k
save_step: 500
