# data configuration
datapath: exp/ddpm-02/samples/ddpm-02-train.pt
num_sample: 50000
t_dim: 65
t_step: 1
dimension: 2
epsilon: 0.00001

# validation data
val_datapath: exp/ddpm-02/samples/ddpm-02-test.pt
num_val_data: 5000
# test data
test_datapath: exp/ddpm-02/samples/ddpm-02-test.pt
# score model
score_path: exp/ddpm-02/ckpts/ddpm-final.pt
temb_dim: 1
x_dim: 2
scale: True
beta_min: 0.1
beta_max: 20
# training
num_epoch: 8000
batchsize: 512
lr: 0.002
milestone: [1000, 2000, 3000, 4000, 5000, 6000, 7000]

# model , 2, 6 - 4, 8
layers: [16, 16, 16, 16, 16]
modes: [8, 8, 8, 8]
fc_dim: 16
activation: 'gelu'

# log
logname: 25gm-v4-16-m8-s65
save_step: 200
use_wandb: True

# if using wandb, specify the following
entity: hzzheng
project: DM-simulation
group: operator-s65-50k

