# data configuration
datapath: data/25gm/25gm-train-v4-s65.pt
num_sample: 5000

# training
num_epoch: 5000
batchsize: 512
lr: 0.001
t_dim: 65
t_step: 16
dimension: 2
epsilon: 0.00001
milestone: [1000, 2000, 3000, 4000]

# model , 2, 6 - 4, 8
layers: [16, 16, 16, 16]
modes: [3, 3, 3]
fc_dim: 8
activation: 'gelu'


# log
logname: 25gm-v4-s5-16-5k
save_step: 500