# data configuration
datapath: data/25gm-train-v4.pt
# training
num_epoch: 2000
batchsize: 1000
t_dim: 50
dimension: 2
epsilon: 0.00001
milestone: [1000]
t_step: 1

# model , 2, 6 - 4, 8
layers: [16, 16, 16, 16]
modes: [16, 16, 16]
fc_dim: 8
activation: 'gelu'


# log
logname: gm-variance4
