# training data
datapath: data/25gm/25gm-train-v4-s65.pt
num_sample: 5000
t_dim: 65
t_step: 8
dimension: 2
epsilon: 0.00001

# validation data
val_datapath: data/25gm/25gm-val-v4-s65.pt
num_val_data: 5000
# test data
test_datapath: data/25gm/25gm-test-v4-s65.pt

# training
num_epoch: 6000
batchsize: 512
lr: 0.002
milestone: [1000, 2000, 3000, 4000, 5000]

# model , 2, 6 - 4, 8
layers: [32, 32, 32, 32, 32]
modes: [4, 4, 4, 4]
fc_dim: 8
activation: 'gelu'


# log
logname: 25gm-v4-s9-32-l4-5k
save_step: 500
use_wandb: False
# if using wandb,