# data configuration
datapath: data/25gm/25gm-train-v4-s65.pt
# training
num_epoch: 3000
batchsize: 1000
lr: 0.002
t_dim: 65
t_step: 16
dimension: 2
epsilon: 0.00001
milestone: [1500]

# model , 2, 6 - 4, 8
layers: [16, 16, 16, 16]
modes: [2, 2, 2]
fc_dim: 8
activation: 'gelu'


# log
logname: 25gm-v4-s5
save_step: 100