# data configuration
datapath: data/25gm/25gm-train-v4-s65.pt
num_sample: 50000
t_dim: 65
t_step: 4
dimension: 2
epsilon: 0.00001

# validation data
val_datapath: data/25gm/25gm-val-v4-s65.pt
num_val_data: 5000
# test data
test_datapath: data/25gm/25gm-test-v4-s65.pt

# training
num_epoch: 8000
batchsize: 512
lr: 0.002
milestone: [1000, 2000, 3000, 4000, 5000, 6000, 7000]

# model , 2, 6 - 4, 8
layers: [16, 16, 16, 16, 16]
modes: [8, 8, 8, 8]
fc_dim: 16
activation: 'leaky_relu'

# log
logname: 25gm-v4-16-s17
save_step: 200
use_wandb: True

# if using wandb, specify the following
entity: hzzheng
project: Diffusion-Gaussian
group: operator-s17-50k
