# training data
datapath: exp/ddpm-02/samples/ddpm-02-train.pt
num_sample: 50000
t_dim: 65
t_step: 32
dimension: 2
epsilon: 0.00001

# validation data
val_datapath: exp/ddpm-02/samples/ddpm-02-test.pt
num_val_data: 5000
# test data
test_datapath: exp/ddpm-02/samples/ddpm-02-test.pt

# training
num_epoch: 8000
batchsize: 512
lr: 0.001
milestone: [1000, 2000, 3000, 4000, 5000, 6000, 7000]

# model , 2, 6 - 4, 8
layers: [2, 128, 128, 128, 128, 2]
activation: 'leaky_relu'

# log
logname: 25gm-v4-FCN-128-l4-50k-ddpm
save_step: 200
use_wandb: True

# if using wandb, specify the following
entity: hzzheng
project: Diffusion-Gaussian
group: DirectKD-50k-ddpm