# data configuration
datapath: data/25gm/25gm-train-v4-s65.pt
num_sample: 50000
t_dim: 65
t_step: 1
dimension: 2
epsilon: 0.00001

# validation data
val_datapath: data/25gm/25gm-val-v4-s65.pt
num_val_data: 5000
# test data
test_datapath: data/25gm/25gm-test-v4-s65.pt
# score model
beta_min: 0.1
beta_max: 20

# training
num_epoch: 2000
batchsize: 512
lr: 0.001
milestone: [300, 600, 900, 1200, 1500]
eq_weight: 0.01

# model , 2, 6 - 4, 8
layers: [24, 24, 24, 24, 24]
modes: [8, 8, 8, 8]
fc_dim: 16
activation: 'leaky_relu'

# log
logname: 25gm-v4-24-m8-s65
save_step: 200
use_wandb: True

# if using wandb, specify the following
entity: hzzheng
project: DM-simulation
group: PINO-s65-50k

