# data configuration
datapath: data/25gm/25gm-train-v4-s65.pt

# training
num_epoch: 2000
batchsize: 1000
lr: 0.0002
t_dim: 65
t_step: 16
dimension: 2
epsilon: 0.00001
milestone: [1000]

# model , 2, 6 - 4, 8
layers: [2, 128, 128, 128, 128, 128, 2]
activation: 'gelu'


# log
logname: 25gm-v4-FCN-128
save_step: 500