# training data
datapath: data/cifar10/ode_data_train_t9.pt
num_samples: 5000
t_dim: 9
t_step: 4
epsilon: 0.00001

# validation data
val_datapath: data/cifar10/ode_data_test_t9.pt
num_val_data: 6000
# test data
test_datapath: data/cifar10/ode_data_test_t9.pt

# training
num_epoch: 1000
batchsize: 32
lr: 0.0005
milestone: [100, 300, 500, 700]
num_pad: 0

# log, FP -> fully present, NS-> no skipped connection in the 1st layer.
logname: cifar-unet3d-5k-CO-NS
save_step: 50

# if using wandb, specify the following
entity: hzzheng
project: Diffusion-CIFAR10
group: unet3d-s9-5k-CO-NS