data:
    dataset: "CIFAR10"
    category: "cifar10"
    image_size: 32
    num_channels: 3
    random_flip: True
    centered: True
    datapath: data/cifar10/train
    num_sample: 112000
    epsilon: 0.00001
    t_dim: 33
    t_step: 32

model:
    dropout: 0.0
    name: 'ncsnpp'
    ema_rate: 0.995
    normalization: 'GroupNorm'
    nonlinearity: 'swish'
    nf: 128
    ch_mult: [1, 1, 1]  # (1, 2, 2, 2)
    num_res_blocks: 3
    attn_resolutions: [8, 16]  # (16,)
    resamp_with_conv: True
    conditional: True
    time_conv: False
    init_scale: 0.
    embedding_type: 'positional'
    fourier_scale: 16
    conv_size: 3
    num_modes: 2

training:
    start_iter: 29000
    n_iters: 60_000
    batchsize: 48
    loss: L1

optim:
    optimizer: 'Adam'
    lr: 0.00005  # 2e-4
    milestone: [20_000, 40_000]
    eps: 0.00000001  # 1e-8
    warmup: 5000
    grad_clip: 1.

log:
    logname: cifar-tunet-1008k-kd
    save_step: 10_000
    entity: hzzheng
    project: Diffusion-CIFAR10
    group: TUnet-1008k-kd