data:
    dataset: "CIFAR10"
    category: "cifar10"
    image_size: 32
    num_channels: 3
    random_flip: True
    centered: True
    datapath: data/cifar10/train
    num_sample: 1064000
    epsilon: 0.00001
    t_dim: 33
    t_step: 32

model:
    dropout: 0.0
    name: 'ncsnpp'
    normalization: 'GroupNorm'
    nonlinearity: 'swish'
    nf: 128
    ch_mult: [1, 2, 2, 2]  # (1, 2, 2, 2)
    num_res_blocks: 2
    attn_resolutions: [16, ]  # (16,)
    resamp_with_conv: True
    conditional: True
    time_conv: False
    init_scale: 0.
    embedding_type: 'positional'
    fourier_scale: 16
    conv_size: 3
    num_modes: 2
    ema_rate: 0.995

training:
    start_iter: 0
    n_iters: 50_001
    batchsize: 64
    loss: L1

eval:
    save_step: 5000
    test_fid: True

optim:
    optimizer: 'Adam'
    lr: 0.00002  # 2e-4
    beta1: 0.9
    beta2: 0.98
    eps: 0.00000001  # 1e-8
    milestone: [10_000, 20_00, 40_000]
    warmup: 100
    grad_clip: 1.

log:
    logname: cifar-tunet-1064k-kd
    entity: hzzheng
    project: Diffusion-CIFAR10
    group: TUnet-1064k-kd